# Generated by Django 2.2.6 on 2019-11-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('brief_content', models.TextField()),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True, unique=True)),
                ('password', models.CharField(max_length=30, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('gendle', models.CharField(max_length=30, null=True)),
                ('birth_place', models.CharField(max_length=30, null=True)),
                ('university', models.CharField(max_length=10, null=True)),
                ('age', models.CharField(max_length=30, null=True)),
                ('weigth', models.CharField(max_length=30, null=True)),
                ('heigth', models.CharField(max_length=30, null=True)),
                ('language', models.CharField(max_length=10, null=True)),
                ('birthday', models.CharField(max_length=30, null=True)),
                ('createdate', models.DateTimeField(auto_now=True)),
                ('question1', models.CharField(max_length=30, null=True)),
                ('answer1', models.CharField(max_length=30, null=True)),
                ('question2', models.CharField(max_length=30, null=True)),
                ('answer2', models.CharField(max_length=30, null=True)),
                ('question3', models.CharField(max_length=30, null=True)),
                ('answer3', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
